export const emailRegex = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/

export const sectors = [
  'All Sectors',
  'Advanced manufacturing and materials',
  'Agriculture, food and beverages',
  'Artificial intelligence',
  'Consumer products and services',
  'Energy',
  'Engineering and technology',
  'Finance',
  'Health: Pharmaceuticals and Biotechnology',
  'Healthcare Devices and Supplies',
  'Healthcare Other Services and Technologies',
  'Health: Pharmaceuticals and Biotechnology',
  'Information and Communication Technology (ICT)',
  'Life-science technologies',
  'Micro/nano-electronics and photonics',
  'Security and connectivity',
  'Life-science technologies',
  'Space and Aerospace',
  'Sustainability and circular economy',
  'Transportation',
  'Financial Services',
  'Education',
  'Health',
  'Agriculture',
  'Insurance',
  'Clean Energy',
  'Construction',
  'Mobility / Logistics',
  'Social Impact',
  'Artificial Intelligence',
  'Internet of Things',
  'Mobile',
  'Software as a Service',
  'Sports',
  'B2B',
  'B2C',
  'D2C',
  'Marketplace',
]

export const kvRoles = [
  'Mentor',
  'Angel Investor',
  'Institutional Investor',
  'Strategic Investor',
  'Acquirer',
  'Customer',
  'Innovator',
  'Industry Analyst',
  'Startup Referrer',
  'Members of Press',
  'Service Provider / Partner',
  'Lecturer / Speaker',
  'Consultant / Freelancer',
]

export const founderType = ['Business Leaning Role', 'Technical Leaning Role']