export const emailRegex =
  /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

export const sectors = [
  "All Sectors",
  "Advanced manufacturing and materials",
  "Agriculture, food and beverages",
  "Artificial intelligence",
  "Consumer products and services",
  "Energy",
  "Engineering and technology",
  "Finance",
  "Health: Pharmaceuticals and Biotechnology",
  "Healthcare Devices and Supplies",
  "Healthcare Other Services and Technologies",
  "Health: Pharmaceuticals and Biotechnology",
  "Information and Communication Technology (ICT)",
  "Life-science technologies",
  "Micro/nano-electronics and photonics",
  "Security and connectivity",
  "Life-science technologies",
  "Space and Aerospace",
  "Sustainability and circular economy",
  "Transportation",
  "Financial Services",
  "Education",
  "Health",
  "Agriculture",
  "Insurance",
  "Clean Energy",
  "Construction",
  "Mobility / Logistics",
  "Social Impact",
  "Artificial Intelligence",
  "Internet of Things",
  "Mobile",
  "Software as a Service",
  "Sports",
  "B2B",
  "B2C",
  "D2C",
  "Marketplace",
];

export const kvRoles = [
  "Mentor",
  "Angel Investor",
  "Institutional Investor",
  "Strategic Investor",
  "Acquirer",
  "Customer",
  "Innovator",
  "Industry Analyst",
  "Startup Referrer",
  "Members of Press",
  "Service Provider / Partner",
  "Lecturer / Speaker",
  "Consultant / Freelancer",
];

export const founderType = ["Business Leaning Role", "Technical Leaning Role"];

export const hearOption = [
  "news",
  "social media",
  "internet search",
  "referral from startup",
  "referral from investor",
];

export const startupValidation = [
  "fundRaising.capTable.amountRaised",
  "fundRaising.capTable.amountInvestedByFounders",
  "fundRaising.financialProjection.files",
  "fundRaising.fundingAsk.instrumentForRound",
  "fundRaising.fundingAsk.numberOfRounds",
  "fundRaising.fundingAsk.fundraisingAmount",
  "fundRaising.previousRound.instrumentForRound",
  "fundRaising.previousRound.numberOfRounds",
  "fundRaising.previousRound.fundraisingAmount",
  "fundRaising.previousRound.dilution",
  "fundRaising.previousRound.preMoneyValuation",
  "fundRaising.previousRound.postMoneyValuation",
  "pitchDeck.pitchDeckFile",
  "pitchDeck.pitchDeckVideo",
  "team.avatar",
  "team.briefIntroduction",
  "team.gender",
  "team.city",
  "team.country",
  "team.email",
  "team.firstName",
  "team.lastName",
  "team.state",
  "team.mobile_number",
  "startUpProfile.logo",
  "startUpProfile.elevatorPitch",
  "startUpProfile.brand",
  "startUpProfile.acceleratorName",
  "startUpProfile.businessSector",
  "startUpProfile.companySize",
  "startUpProfile.registrationNumber",
  "startUpProfile.startupStage",
  "product.description",
  "product.competitiveEdge",
];

export const features = [
  "Opportunities",
  "Schedule",
  "Event",
  "To do List",
  "Selection Process",
  "Networking",
  "Dashboard",
  "Program",
  "Assignment",
  "Evaluation",
  "Deal room",
  "Application",
  "Partners",
  "E-Academy",
];

export const investorRoles = [
  "Super Admin",
  "Sub Admin",
  "Investor",
  "Mentor",
  "Start-up",
  "Add role",
];

// 'fundRaising.previousRound.numberOfRounds',
// 'fundRaising.previousRound.fundraisingAmount',
// 'fundRaising.previousRound.dilution',
// 'fundRaising.previousRound.preMoneyValuation',
// 'fundRaising.previousRound.postMoneyValuation',
// 'pitchDeck.pitchDeckFile',
// 'pitchDeck.pitchDeckVideo',
// 'team.avatar',
// 'team.briefIntroduction',
// 'team.gender',
// 'team.city',
// 'team.country',
// 'team.email',
// 'team.firstName',
// 'team.lastName',
// 'team.state',
// 'team.mobile_number',
// 'startUpProfile.logo',
// 'startUpProfile.elevatorPitch',
// 'startUpProfile.brand',
// 'startUpProfile.acceleratorName',
// 'startUpProfile.businessSector',
// 'startUpProfile.companySize',
// 'startUpProfile.registrationNumber',
// 'startUpProfile.startupStage',
// 'product.description',
// 'product.competitiveEdge',
